### ISSUE TITLE
Opt Assertion `Val && "isa<> used on a null pointer"' failed

### ISSUE THREAD

**Issue by vineodd** [bprail/contech#207]
Recently I pulled the latest Contech and found failed in instrumenting every application. To exclude the possibilities of my poor code writing, I wrote a hello world c++ program and used scripts/contech_wrapper_par++.py. I always got the following error:

> python scripts/contech_wrapper_par++.py \~/contech/test.cpp 
 clang++ --verbose -pthread /home/xuchen/contech/test.cpp -emit-llvm -c -o /home/xuchen/contech/test.o
clang version 3.9.1-4ubuntu3~14.04.3 (tags/RELEASE_391/rc2)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9.3
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/lib/llvm-3.9/bin/clang" -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -v -dwarf-column-info -debugger-tuning=gdb -coverage-file /home/xuchen/contech/test.o -resource-dir /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8 -internal-isystem /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/backward -internal-isystem /usr/local/include -internal-isystem /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir /home/xuchen/contech -ferror-limit 19 -fmessage-length 0 -pthread -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -fdiagnostics-show-option -o /home/xuchen/contech/test.o -x c++ /home/xuchen/contech/test.cpp
clang -cc1 version 3.9.1 based upon LLVM 3.9.1 default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/include"
ignoring duplicate directory "/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8"
#include "..." search starts here:
#include <...> search starts here:
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/x86_64-linux-gnu/c++/4.8
 /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/backward
 /usr/local/include
 /usr/lib/llvm-3.9/bin/../lib/clang/3.9.1/include
 /usr/include/x86_64-linux-gnu
 /usr/include
 End of search list.
 mkdir -p /tmp/tmpo9D_um
 llvm-link -v  /home/xuchen/contech/test.o  -o a.out.link.bc
Loading '/home/xuchen/contech/test.o'
Linking in '/home/xuchen/contech/test.o'
Writing bitcode...
opt -load=/home/xuchen/contech/llvm-contech/lib/LLVMContech.so -Contech a.out.link.bc -o a.out_ct.link.bc -ContechState /home/xuchen/contech/scripts/output/contechStateFile.temp
_GLOBAL__sub_I_test.cpp
__cxx_global_var_init
main
SKIP: __ctGetBufferPos
SKIP: __ctStoreBasicBlock
SKIP: __ctStoreBasicBlockComplete
SKIP: __ctExtendPathInfo
SKIP: __ctStorePathInfo
SKIP: __ctStoreMemOp
SKIP: __ctGetBuffer
SKIP: __ctGetBufferPtr
SKIP: __ctInitCilkSync
SKIP: __ctAllocateLocalBuffer
SKIP: __ctOMPPushParent
SKIP: __ctOMPPopParent
SKIP: __ctOMPProcessJoinStack
SKIP: __ctAllocateCTid
SKIP: __ctGetLocalNumber
SKIP: __ctGetCurrentTick
SKIP: __ctAllocateTicket
SKIP: __ctPeekParent
SKIP: __ctStoreSync
SKIP: __ctOMPThreadCreate
SKIP: __ctOMPThreadJoin
SKIP: __ctOMPTaskCreate
SKIP: __ctCheckBufferSize
SKIP: __ctCheckBufferBySize
SKIP: __ctStoreLoopExit
SKIP: __ctStoreLoopEntryShort
SKIP: __ctStoreLoopEntry
SKIP: __ctQueueBuffer
SKIP: __ctOMPTaskJoin
SKIP: __ctStoreBarrier
SKIP: __ctAddThreadInfo
SKIP: __ctStoreMPITransfer
SKIP: __ctStoreMPIAllOne
SKIP: __ctStoreMPIWait
SKIP: __ctRecordCilkFrame
SKIP: __ctRecordCilkSync
SKIP: __ctRestoreCilkFrame
SKIP: __ctCilkPromoteParent
SKIP: __ctWriteElideGVEvents
SKIP: __ctStoreGVEvent
SKIP: __ctStoreThreadCreate
SKIP: __ctStoreThreadJoin
SKIP: __ctStoreMemoryEvent
SKIP: __ctStoreBulkMemoryEvent
SKIP: __ctOMPStoreInOutDeps
SKIP: __ctThreadCreateActual
Tail Dup Count: 0
Incorrect number of arguments passed to called function!
  call void @__ctStoreMemOp(i8* %"Cast to Support Type", i32 0, i8* %storeBlock0), !ContechInst !1
LLVM ERROR: Broken function found, compilation aborted!
Fatal error in pcall

Is there any solutions?

**Comment by bprail** [comment]
Should be fixed in the above commit.
